# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{acts_as_muschable}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Moviepilot"]
  s.date = %q{2010-03-04}
  s.description = %q{Do not use me unless you are not you but somebody else.}
  s.email = %q{jannis@moviepilot.de}
  s.files = [
    ".gitignore",
     "Rakefile",
     "VERSION",
     "acts_as_muschable.gemspec",
     "init.rb",
     "lib/acts_as_muschable.rb",
     "rails/init.rb",
     "spec/acts_as_muschable/acts_as_muschable_spec.rb",
     "spec/acts_as_muschable/integration_spec.rb",
     "spec/schema.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/moviepilot/acts_as_muschable}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Easy peasy model sharding}
  s.test_files = [
    "spec/acts_as_muschable/acts_as_muschable_spec.rb",
     "spec/acts_as_muschable/integration_spec.rb",
     "spec/schema.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end
